src/app/FileBrowser/FileBrowser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('browser/', include('browser.urls')),
    path('admin/', admin.site.urls),
]

src/app/FileBrowser/browser/urls.py
from django.urls import path
from . import views

app_name = 'browser'
urlpatterns = [
    path('', views.default, name = 'default' ),
    path('help/', views.help, name = 'help'),
    path('systems/dt/', views.dtSystems.as_view(), name = 'dt'),
    path('systems/<int:serialNumberInserv>', views.files, name = 'files'),
    path('systems/', views.systems, name = 'systems' ),
    path('download/<slug:fileID>', views.download, name = 'download'),
    path('login/', views.loginView, name = 'login' ),
	path('logout/', views.logoutView, name = 'logout' )
]

src/app/FileBrowser/browser/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.

from django.db import models


class System(models.Model):
    serialNumberInserv = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=45)
    tenants = ArrayField(models.CharField(max_length = 200), blank = True, null = True)
    recentDate = models.DateField()
    capacity = models.FloatField(blank = True, null = True)
    def __str__(self):
        return str(self.serialNumberInserv)

    def __int__(self):
        return self.serialNumberInserv

class customUser(models.Model):
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=100)
    role = models.CharField(max_length=20)

class File(models.Model):
    FileID = models.CharField(primary_key=True, max_length = 45)
    name = models.CharField(max_length=35)
    filePath = models.CharField(max_length=100)
    dataDate = models.DateField()
    SystemID = models.ForeignKey(System, on_delete = models.CASCADE)
    capacity = models.FloatField()

    def __str__(self):
        return self.FileID

src/app/FileBrowser/browser/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20)

src/app/FileBrowser/browser/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.template import loader
from .models import *
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.hashers import make_password, check_password
from django.core.exceptions import ObjectDoesNotExist
from .forms import *
import json
from django.utils.encoding import smart_str
import os
from sys import platform
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.views.decorators.cache import never_cache
from django.db.models import Q

# Create your views here.
"""
def index(request):
    return HttpResponse("Welcome to HPE File Browser 0.0.1")
"""
class dtSystems(BaseDatatableView):
    model = System
    columns = ["serialNumberInserv", "name", "recentDate", "capacity"]
    order_columns = ["serialNumberInserv", "name", "recentDate", "capacity"]

    def filter_queryset(self, qs):
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(Q(name__istartswith=search) | Q(serialNumberInserv__istartswith=search))
        username = str(self.request.session['username'])
        return qs.filter(tenants__contains = [username])

@never_cache
def systems(request):
    if not request.session.has_key('username'):
        return redirect("browser:login")
    username = str(request.session['username'])
    try:
        system_list = System.objects.filter(tenants__contains = [username]).order_by('serialNumberInserv')[:100]
    except:
        return render(request, 'browser/error.html')
    return render(request, 'browser/systems_page.html', {'system_list' : system_list})

@never_cache
def files(request, serialNumberInserv):
    if not request.session.has_key('username'):
        return redirect("browser:login")
    try:
        system = get_object_or_404(System, serialNumberInserv=serialNumberInserv)
    except:
        return render(request, 'browser/error.html')
    tenants = system.tenants
    username = str(request.session['username'])
    if username in tenants:
        files = get_list_or_404(File, SystemID = serialNumberInserv)
        system = get_object_or_404(System, serialNumberInserv=serialNumberInserv)
        return render(request, 'browser/files_page.html', {'file_list':files, 'companyID':serialNumberInserv, 
            'companyName':system.name})
    else:
        return redirect("browser:systems")

@never_cache
def download(request, fileID):
    if not request.session.has_key('username'):
        return redirect("browser:login")
    try:
        file = get_object_or_404(File, FileID=fileID)
    except:
        return render(request, 'browser/error.html')
    if platform == "linux" or platform == "linux2" or platform == 'darwin':
    # linux or OS X
        f_path = 'browser/static/'
    elif platform == "win32":
    # Windows...
        f_path = r'browser\\'
    systemID = file.SystemID
    system = get_object_or_404(System, serialNumberInserv=systemID)
    tenants = system.tenants
    username = str(request.session['username'])
    if username in tenants:
        with open(f_path+file.filePath) as f:
            data = json.load(f)
        response = HttpResponse(json.dumps(data, indent=4), content_type='application/force-download')
        response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(file.name)
        return response
    else:
        return redirect("browser:login")

@never_cache
def help(request):
    if not request.session.has_key('username'):
        return redirect("browser:login")
    return render(request, 'browser/help.html', {})

@never_cache
def loginView(request):
    errors = []
    try:
      del request.session['username']
    except:
      pass
    if request.method == 'POST':
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            usr = login_form.cleaned_data['username']
            pswd = login_form.cleaned_data['password']
            try:
                u = customUser.objects.get(username=usr)
                if check_password(pswd, u.password):
                    request.session['username'] = usr
                    return redirect("browser:systems")
                else:
                    errors = ['invalid username or password']
            except ObjectDoesNotExist:
                errors = ['invalid username or password']
        else:
            errors = ['invalid username or password']

    return render(request, 'browser/login.html', {'error' : errors})

@never_cache
def logoutView(request):
    try:
      del request.session['username']
    except:
      pass
    return redirect("browser:login")

@never_cache
def default(request):
    return redirect("browser:systems")

@never_cache
def error_page(request):
    return render(request, 'browser/error.html',status=404)

src/app/FileBrowser/browser/templates/browser/base_generic.html
{% load static %}

<html>
	<head>
		<title>
			File Browser
		</title>
		<link rel="stylesheet" href="{% static 'css/base_generic.css' %}">
		<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	</head>
	<body class="background">
		{% include "browser/header.html" %}
		&nbsp
		&nbsp
		<div id="card-container">
			<div class="card mx-5 my-4 browser-card">
				<div class="card-body">
					{% block content %}
					{% endblock %}
				</div>
			</div>
		</div>
	</body>
</html>

src/app/FileBrowser/browser/templates/browser/error.html
{% extends "browser/base_generic.html" %}
{% load static %}

{% block content %}	

<style>
    .browser-card {
        text-align: center;
        box-shadow: 0px 10px 50px black;
        background-color: bbc1c4 !important;
        margin-right: auto !important;
        margin-left: auto !important;
        margin-top: 6rem !important;
        min-width: 30rem;
        width: 50%;
    }
</style>

<h1>Oops! Nothing to see here.</h1>
<br>
<p>You found a broken link.</p>
<br>

{% endblock %}

src/app/FileBrowser/browser/templates/browser/files_page.html
{% extends "browser/base_generic.html" %}
{% load static %}

{% block content %}	
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/table_page.css' %}">	
	<link rel="stylesheet" href="{% static 'css/datatables.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/files_page.js' %}"></script>
	
	<!-- Files Header -->
	<div id="FileHeader">
		<h1 class="mb-2 file-header">{% if companyName %}{{companyName}}'s Files
									{% else %}All Files{% endif %}</h1>
		<h5 class="system-id">{% if companyID %}System ID: {{companyID}}{% endif %}</h5>
	</div>

	<!-- Files Table -->
	<div class="table-responsive" style="overflow-x: auto;">
		<table id="files-table" class="table  table-bordered my-5 browser-table">
			<col width= "25%">
			<col width= "25%">
			<col width= "25%">
			<col width= "25%">

			<!-- Column Headers -->
			<thead>
				<tr class="table-secondary">
					<th>File Name</th>
					<th>Date</th>
					<th>Free Capacity</th>
					<th>Download Link</th>
				</tr>
			</thead>

			<!-- Table -->
			<tbody class="table-light">
				{% if file_list %}			
					{% for file in file_list %}
						<tr>
							<td>{{file.FileID}}</td>
							<td>{{file.dataDate|date:"Y-m-d"}}</td>
							<td>{{file.capacity}}%</td>
							<td> <a href="{%url 'browser:download' file.FileID %}" download> Download </a> </td>
						</tr>
					{% endfor %}
				{% endif %}
			</tbody>
		</table>
	</div>

{% endblock %}

src/app/FileBrowser/browser/templates/browser/header.html
<!--Nav Bar-->
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'css/base_generic.css' %}">
	<!-- Bootstrap core CSS -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!--
	<!-- Jquery and datatables
    <link rel="stylesheet" type="text/css" href="../css/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="../css/dataTables.css">
    <!-- Bootstrap core and jquery-ui JavaScript
    <script src="../js/jquery-3.3.1.min.js"></script>
    <script src="../js/bootstrap.min.js"></script>
    <script src="../js/jquery-ui.min.js"></script>
    <script src="../js/dataTables.min.js"></script>
	-->
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #222325;">
  <a class="navbar-brand" href="/browser/" style="color:#08C969">FileSublime</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'browser:systems' %}">Systems <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'browser:logout' %}">Logout</a>
      <a class="nav-item nav-link" href="{% url 'browser:help' %}">Help</a>
    </div>
  </div>
</nav>

</body>
</html>

src/app/FileBrowser/browser/templates/browser/help.html
{% extends 'browser/base_generic.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/help.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/help.js' %}"></script>

<h1>FileSublime<span class="badge badge-secondary"></span></h1>

<div id="help-container" class="center-section">
	<ul class="nav nav-tabs">
		<li class="nav-item active"><a class="nav-link" href="#welcome">Welcome</a></li>
		<li class="nav-item"><a class="nav-link" href="#tutorial">Tutorial</a></li>
	</ul>

	<div class="tab-content">
		<div id="welcome" class="tab-pane fade in active help-section">
			<h4>Welcome</h4>
			<p>
				For HPE support users who need to download specific HPE system files, FileSublime
				is a file browser that provides access to raw support files, previously only
				indirectly available through other support tools. Our product is a simple and
				direct way to retrieve raw data.
			</p>
			<p>
				FileSublime is used to filter through specific Json files which contain certain
				identifying information, such as system and date.
			</p>
		</div>
		<div id="tutorial" class="tab-pane fade help-section">
			<h4>Navigation Bar</h4>
			<p>
				At the top of every page there is the navigation bar. You can use this to help
				navigate the web app or view the help section. There is a “Systems” button that
				brings you to the systems page, a “Logout” button that logs the current user out
				and a “Help” button that brings up the help page.
			</p>
			<h4>Systems Page</h4>
			<p>
				By default, you are brought to the systems page. This lists all the systems in a
				table along with some identifying information. It shows a system’s system ID,
				associated company name and the number of files associated with that system. You 
				can use the search bar in the upper right to filter systems and find the one you 
				are looking for. To filter each column you can click the column header to sort in either ascending or descending order. To view the files for a system, click on the respective system’s
				system ID. This will bring you to the system’s file page. 
			</p>
			<h4>Files Page</h4>
			<p>
				On the file page you can view all the files associated with a system along with
				some identifying information. At the top of the page, you can see the system you
				are browsing’s company name and the system ID. Below that is a table listing all
				of the files for that system. Each file has a file name and date. You can search
				for files within a system by using the search bar on the top right hand corner of
				the table. Once you find the file you want to download, you can click “Download” 
				on that file’s table row.
			</p>
			<h4>Capacity Alert</h4>
			<img style="outline-style: solid;" src="{% static 'images/Gradient Bar.png' %}" alt="0% Capacity is dark red, 30% is light red and >30% is white." align="middle" width="50%" >
			<p>
				You may notice that some cells for the free capacity are colored in different in 
				different shades of red. This is to show how much capacity is left on a specific 
				system. The darker red color, the closer to 0% free capacity is left on the system.
				The ligher the red color the closer to 30% free capacity is left on the system. Any
				system that has more than 30% free capacity will be colored white. 
			</p>
		</div>
	</div>
</div>

<!--
<p>
    <a class ="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">Q&A</a>
</p>
<div class="collapse" id="collapseExample">
    <div class="card card-body">
        Search for file by click on the systems link and search for system you are interested in.
    </div>
</div>
-->
{% endblock %}

src/app/FileBrowser/browser/templates/browser/index.html
{% load static %}

{% if file_list %}
  <table>
    <tr><th>System ID</th><th>File ID</th><tr>
    {% for file in file_list %}
      <tr>
        <td>{{file.SystemID}}</td><td> <a href = "{%static file.filePath %}" download> {{file.FileID}} </a></td>
      </tr>
    {% endfor %}
  </table>
{% endif %}

src/app/FileBrowser/browser/templates/browser/login.html
{% extends 'browser/base_generic.html' %}
{% load static %}

{% block content %}
<style>
    .browser-card {
        text-align: center;
        box-shadow: 0px 10px 50px black;
        background-color: bbc1c4 !important;
        margin-right: auto !important;
        margin-left: auto !important;
        margin-top: 6rem !important;
        min-width: 30rem;
        width: 50%;
    }
    .login-form {
        margin: auto;
        text-align: left;
        width: 50%;
    }
    .login-form input {
        margin-top: 8px;
    }
    .btn {
        margin: auto;
        margin-top: 20px;
    }
    .navbar {
        display: none;
    }
</style>


<h1>FileSublime<span class="badge badge-secondary"></span></h1>
<p>
    <form method="post">
      {% csrf_token %}
        <div class="login-form">
            <h4>Log-in</h4>
            <input type="text" placeholder="Username" name="username" class="form-control" id="usr">
            <input type="password" placeholder="Password" name="password" class="form-control" id="psw">
            {% if error %}          
                    <p style="color:red;">{{error.0}}</p>
            {% endif %}
        </div>
        <button id="submit" type="submit" class ="btn btn-primary" data-toggle="collapse" role="button" aria-expanded="false">Login</button>
    </form>

</p>
{% endblock %}

src/app/FileBrowser/browser/templates/browser/systems_page.html
{% extends "browser/base_generic.html" %}
{% load static %}

{% block content %}	
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/table_page.css' %}">	
	<link rel="stylesheet" href="{% static 'css/datatables.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/systems_page.js' %}"></script>
	
	<!-- Systems Header -->
	<div id="SystemHeader">
		<h1 class="mb-2 file-header">Systems</h1>
		<!--<h5 class="system-id">System ID: 38510</h5>-->
	</div>

	<!-- Systems Table -->
	<table id="systems-table" class="table table-bordered my-5 browser-table">
		<col width= "25%">
		<col width= "25%">
		<col width= "25%">
		<col width= "25%">

		<!-- Column Headers -->
		<thead>
			<tr class="table-secondary">
				<th>System ID</th>
				<th>Company Name</th> 
				<th>Most Recent File Date</th>
				<th>Free Capacity</th>
			</tr>
		</thead>

		<!-- Table -->
		<tbody class="table-light">
			{% if system_list %}			
				{% for system in system_list %}
					<tr> 
						<td> <a href="{% url 'browser:files' system.serialNumberInserv %}"> {{system.serialNumberInserv}} </a> </td>
						<td>{{system.name}}</td>
						<td>{{system.recentDate}}</td>

						<td class="capacity">{{system.capacity}}%</td>						
					</tr>
				{% endfor %}
			{% endif %}
		</tbody>
	</table>
{% endblock %}